export
    KTR_INFBOUND,
    KTR_OBJGOAL_MINIMIZE,
    KTR_OBJGOAL_MAXIMIZE,
    KTR_OBJTYPE_GENERAL,
    KTR_OBJTYPE_LINEAR,
    KTR_OBJTYPE_QUADRATIC,
    KTR_CONTYPE_GENERAL,
    KTR_CONTYPE_LINEAR,
    KTR_CONTYPE_QUADRATIC,
    KTR_VARTYPE_CONTINUOUS,
    KTR_VARTYPE_INTEGER,
    KTR_VARTYPE_BINARY,
    KTR_FNTYPE_UNCERTAIN,
    KTR_FNTYPE_CONVEX,
    KTR_FNTYPE_NONCONVEX,
    KTR_RC_BEGINEND,
    KTR_RC_EVALFC,
    KTR_RC_EVALGA,
    KTR_RC_EVALH,
    KTR_RC_EVALX0,
    KTR_RC_FINISHED,
    KTR_RC_NEWPOINT,
    KTR_RC_EVALHV,
    KTR_RC_EVALH_NO_F,
    KTR_RC_EVALHV_NO_F,
    KTR_RC_NODE,
    KTR_RC_MSPROCESS,
    KTR_RC_OPTIMAL,
    KTR_RC_NEAR_OPT,
    KTR_RC_FEAS_XTOL,
    KTR_RC_FEAS_NO_IMPROVE,
    KTR_RC_FEAS_FTOL,
    KTR_RC_INFEASIBLE,
    KTR_RC_INFEAS_XTOL,
    KTR_RC_INFEAS_NO_IMPROVE,
    KTR_RC_INFEAS_MULTISTART,
    KTR_RC_INFEAS_CON_BOUNDS,
    KTR_RC_INFEAS_VAR_BOUNDS,
    KTR_RC_UNBOUNDED,
    KTR_RC_ITER_LIMIT,
    KTR_RC_TIME_LIMIT,
    KTR_RC_FEVAL_LIMIT,
    KTR_RC_MIP_EXH,
    KTR_RC_MIP_FEAS_TERM,
    KTR_RC_MIP_SOLVE_LIMIT,
    KTR_RC_MIP_NODE_LIMIT,
    KTR_RC_CALLBACK_ERR,
    KTR_RC_LP_SOLVER_ERR,
    KTR_RC_EVAL_ERR,
    KTR_RC_OUT_OF_MEMORY,
    KTR_RC_USER_TERMINATION,
    KTR_RC_OPEN_FILE_ERR,
    KTR_RC_BAD_N_OR_F,
    KTR_RC_BAD_CONSTRAINT,
    KTR_RC_BAD_JACOBIAN,
    KTR_RC_BAD_HESSIAN,
    KTR_RC_BAD_CON_INDEX,
    KTR_RC_BAD_JAC_INDEX,
    KTR_RC_BAD_HESS_INDEX,
    KTR_RC_BAD_CON_BOUNDS,
    KTR_RC_BAD_VAR_BOUNDS,
    KTR_RC_ILLEGAL_CALL,
    KTR_RC_BAD_KCPTR,
    KTR_RC_NULL_POINTER,
    KTR_RC_BAD_INIT_VALUE,
    KTR_RC_NEWPOINT_HALT,
    KTR_RC_BAD_LICENSE,
    KTR_RC_BAD_PARAMINPUT,
    KTR_RC_LINEAR_SOLVER_ERR,
    KTR_RC_INTERNAL_ERROR,
    KTR_PARAM_NEWPOINT,
    KTR_PARAM_HONORBNDS,
    KTR_PARAM_ALGORITHM,
    KTR_PARAM_ALG,
    KTR_PARAM_BAR_MURULE,
    KTR_PARAM_BARRULE,
    KTR_PARAM_BAR_FEASIBLE,
    KTR_PARAM_FEASIBLE,
    KTR_PARAM_GRADOPT,
    KTR_PARAM_HESSOPT,
    KTR_PARAM_BAR_INITPT,
    KTR_PARAM_LPSOLVER,
    KTR_PARAM_MAXCGIT,
    KTR_PARAM_MAXIT,
    KTR_PARAM_OUTLEV,
    KTR_PARAM_OUTMODE,
    KTR_PARAM_SCALE,
    KTR_PARAM_SHIFTINIT,
    KTR_PARAM_SOC,
    KTR_PARAM_DELTA,
    KTR_PARAM_BAR_FEASMODETOL,
    KTR_PARAM_FEASMODETOL,
    KTR_PARAM_FEASTOL,
    KTR_PARAM_FEASTOLABS,
    KTR_PARAM_MAXTIMECPU,
    KTR_PARAM_BAR_INITMU,
    KTR_PARAM_MU,
    KTR_PARAM_OBJRANGE,
    KTR_PARAM_OPTTOL,
    KTR_PARAM_OPTTOLABS,
    KTR_PARAM_PIVOT,
    KTR_PARAM_XTOL,
    KTR_PARAM_DEBUG,
    KTR_PARAM_MULTISTART,
    KTR_PARAM_MSMAXSOLVES,
    KTR_PARAM_MSMAXBNDRANGE,
    KTR_PARAM_MSMAXTIMECPU,
    KTR_PARAM_MSMAXTIMEREAL,
    KTR_PARAM_LMSIZE,
    KTR_PARAM_BAR_MAXCROSSIT,
    KTR_PARAM_MAXCROSSIT,
    KTR_PARAM_MAXTIMEREAL,
    KTR_PARAM_PRECOND,
    KTR_PARAM_BLASOPTION,
    KTR_PARAM_BAR_MAXREFACTOR,
    KTR_PARAM_BAR_MAXBACKTRACK,
    KTR_PARAM_BLASOPTIONLIB,
    KTR_PARAM_OUTAPPEND,
    KTR_PARAM_OUTDIR,
    KTR_PARAM_CPLEXLIB,
    KTR_PARAM_BAR_PENRULE,
    KTR_PARAM_BAR_PENCONS,
    KTR_PARAM_MSNUMTOSAVE,
    KTR_PARAM_MSSAVETOL,
    KTR_PARAM_PRESOLVEDEBUG,
    KTR_PARAM_MSTERMINATE,
    KTR_PARAM_MSSTARTPTRANGE,
    KTR_PARAM_INFEASTOL,
    KTR_PARAM_LINSOLVER,
    KTR_PARAM_BAR_DIRECTINTERVAL,
    KTR_PARAM_PRESOLVE,
    KTR_PARAM_PRESOLVE_TOL,
    KTR_PARAM_BAR_SWITCHRULE,
    KTR_PARAM_HESSIAN_NO_F,
    KTR_PARAM_MA_TERMINATE,
    KTR_PARAM_MA_MAXTIMECPU,
    KTR_PARAM_MA_MAXTIMEREAL,
    KTR_PARAM_MSSEED,
    KTR_PARAM_MA_OUTSUB,
    KTR_PARAM_MS_OUTSUB,
    KTR_PARAM_XPRESSLIB,
    KTR_PARAM_TUNER,
    KTR_PARAM_TUNER_OPTIONSFILE,
    KTR_PARAM_TUNER_MAXTIMECPU,
    KTR_PARAM_TUNER_MAXTIMEREAL,
    KTR_PARAM_TUNER_OUTSUB,
    KTR_PARAM_TUNER_TERMINATE,
    KTR_PARAM_LINSOLVER_OOC,
    KTR_PARAM_BAR_RELAXCONS,
    KTR_PARAM_MIP_METHOD,
    KTR_PARAM_MIP_BRANCHRULE,
    KTR_PARAM_MIP_SELECTRULE,
    KTR_PARAM_MIP_INTGAPABS,
    KTR_PARAM_MIP_INTGAPREL,
    KTR_PARAM_MIP_MAXTIMECPU,
    KTR_PARAM_MIP_MAXTIMEREAL,
    KTR_PARAM_MIP_MAXSOLVES,
    KTR_PARAM_MIP_INTEGERTOL,
    KTR_PARAM_MIP_OUTLEVEL,
    KTR_PARAM_MIP_OUTINTERVAL,
    KTR_PARAM_MIP_OUTSUB,
    KTR_PARAM_MIP_DEBUG,
    KTR_PARAM_MIP_IMPLICATNS,
    KTR_PARAM_MIP_GUB_BRANCH,
    KTR_PARAM_MIP_KNAPSACK,
    KTR_PARAM_MIP_ROUNDING,
    KTR_PARAM_MIP_ROOTALG,
    KTR_PARAM_MIP_LPALG,
    KTR_PARAM_MIP_TERMINATE,
    KTR_PARAM_MIP_MAXNODES,
    KTR_PARAM_MIP_HEURISTIC,
    KTR_PARAM_MIP_HEUR_MAXIT,
    KTR_PARAM_MIP_HEUR_MAXTIMECPU,
    KTR_PARAM_MIP_HEUR_MAXTIMEREAL,
    KTR_PARAM_MIP_PSEUDOINIT,
    KTR_PARAM_MIP_STRONG_MAXIT,
    KTR_PARAM_MIP_STRONG_CANDLIM,
    KTR_PARAM_MIP_STRONG_LEVEL,
    KTR_PARAM_PAR_NUMTHREADS,
    KTR_PARAM_PAR_CONCURRENT_EVALS,
    KTR_PARAM_PAR_BLASNUMTHREADS,
    KTR_PARAM_PAR_LSNUMTHREADS,
    KTR_NEWPOINT_NONE,
    KTR_NEWPOINT_SAVEONE,
    KTR_NEWPOINT_SAVEALL,
    KTR_NEWPOINT_USER,
    KTR_HONORBNDS_NO,
    KTR_HONORBNDS_ALWAYS,
    KTR_HONORBNDS_INITPT,
    KTR_ALG_AUTOMATIC,
    KTR_ALG_AUTO,
    KTR_ALG_BAR_DIRECT,
    KTR_ALG_BAR_CG,
    KTR_ALG_ACT_CG,
    KTR_ALG_IPDIRECT,
    KTR_ALG_IPCG,
    KTR_ALG_ACTIVE,
    KTR_ALG_MULTI,
    KTR_BAR_MURULE_AUTOMATIC,
    KTR_BAR_MURULE_AUTO,
    KTR_BAR_MURULE_MONOTONE,
    KTR_BAR_MURULE_ADAPTIVE,
    KTR_BAR_MURULE_PROBING,
    KTR_BAR_MURULE_DAMPMPC,
    KTR_BAR_MURULE_FULLMPC,
    KTR_BAR_MURULE_QUALITY,
    KTR_BAR_FEASIBLE_NO,
    KTR_BAR_FEASIBLE_STAY,
    KTR_BAR_FEASIBLE_GET,
    KTR_BAR_FEASIBLE_GET_STAY,
    KTR_FEASIBLE_NO,
    KTR_FEASIBLE_ALWAYS,
    KTR_GRADOPT_EXACT,
    KTR_GRADOPT_FORWARD,
    KTR_GRADOPT_CENTRAL,
    KTR_GRADOPT_USER_FORWARD,
    KTR_GRADOPT_USER_CENTRAL,
    KTR_HESSOPT_EXACT,
    KTR_HESSOPT_BFGS,
    KTR_HESSOPT_SR1,
    KTR_HESSOPT_FINITE_DIFF,
    KTR_HESSOPT_PRODUCT,
    KTR_HESSOPT_LBFGS,
    KTR_BAR_INITPT_AUTO,
    KTR_BAR_INITPT_YES,
    KTR_BAR_INITPT_STRAT1,
    KTR_BAR_INITPT_NO,
    KTR_BAR_INITPT_STRAT2,
    KTR_BAR_INITPT_STRAT3,
    KTR_LP_INTERNAL,
    KTR_LP_CPLEX,
    KTR_LP_XPRESS,
    KTR_OUTLEV_NONE,
    KTR_OUTLEV_SUMMARY,
    KTR_OUTLEV_MAJORIT10,
    KTR_OUTLEV_ITER_10,
    KTR_OUTLEV_MAJORIT,
    KTR_OUTLEV_ITER,
    KTR_OUTLEV_ALLIT,
    KTR_OUTLEV_ITER_VERBOSE,
    KTR_OUTLEV_ALLIT_X,
    KTR_OUTLEV_ITER_X,
    KTR_OUTLEV_ALL,
    KTR_OUTMODE_SCREEN,
    KTR_OUTMODE_FILE,
    KTR_OUTMODE_BOTH,
    KTR_SCALE_NEVER,
    KTR_SCALE_ALLOW,
    KTR_SOC_NO,
    KTR_SOC_MAYBE,
    KTR_SOC_YES,
    KTR_DEBUG_NONE,
    KTR_DEBUG_PROBLEM,
    KTR_DEBUG_EXECUTION,
    KTR_MULTISTART_NO,
    KTR_MULTISTART_YES,
    KTR_PRECOND_NONE,
    KTR_PRECOND_CHOL,
    KTR_BLASOPTION_KNITRO,
    KTR_BLASOPTION_INTEL,
    KTR_BLASOPTION_DYNAMIC,
    KTR_OUTAPPEND_NO,
    KTR_OUTAPPEND_YES,
    KTR_BAR_PENRULE_AUTO,
    KTR_BAR_PENRULE_SINGLE,
    KTR_BAR_PENRULE_FLEX,
    KTR_BAR_PENCONS_AUTO,
    KTR_BAR_PENCONS_NONE,
    KTR_BAR_PENCONS_ALL,
    KTR_BAR_PENCONS_EQUALITIES,
    KTR_BAR_PENCONS_INFEAS,
    KTR_PRESOLVEDBG_NONE,
    KTR_PRESOLVEDBG_BASIC,
    KTR_PRESOLVEDBG_VERBOSE,
    KTR_MSTERMINATE_MAXSOLVES,
    KTR_MSTERMINATE_OPTIMAL,
    KTR_MSTERMINATE_FEASIBLE,
    KTR_LINSOLVER_AUTO,
    KTR_LINSOLVER_INTERNAL,
    KTR_LINSOLVER_HYBRID,
    KTR_LINSOLVER_DENSEQR,
    KTR_LINSOLVER_MA27,
    KTR_LINSOLVER_MA57,
    KTR_LINSOLVER_MKLPARDISO,
    KTR_PRESOLVE_NONE,
    KTR_PRESOLVE_BASIC,
    KTR_PRESOLVE_ADVANCED,
    KTR_BAR_SWITCHRULE_AUTO,
    KTR_BAR_SWITCHRULE_NEVER,
    KTR_BAR_SWITCHRULE_LEVEL1,
    KTR_BAR_SWITCHRULE_LEVEL2,
    KTR_HESSIAN_NO_F_FORBID,
    KTR_HESSIAN_NO_F_ALLOW,
    KTR_MA_TERMINATE_ALL,
    KTR_MA_TERMINATE_OPTIMAL,
    KTR_MA_TERMINATE_FEASIBLE,
    KTR_MA_OUTSUB_NONE,
    KTR_MA_OUTSUB_YES,
    KTR_MS_OUTSUB_NONE,
    KTR_MS_OUTSUB_YES,
    KTR_TUNER_OFF,
    KTR_TUNER_ON,
    KTR_TUNER_OUTSUB_NONE,
    KTR_TUNER_OUTSUB_YES,
    KTR_TUNER_OUTSUB_SUMMARY,
    KTR_TUNER_OUTSUB_ALL,
    KTR_TUNER_TERMINATE_ALL,
    KTR_TUNER_TERMINATE_OPTIMAL,
    KTR_TUNER_TERMINATE_FEASIBLE,
    KTR_LINSOLVER_OOC_NO,
    KTR_LINSOLVER_OOC_MAYBE,
    KTR_LINSOLVER_OOC_YES,
    KTR_BAR_RELAXCONS_NONE,
    KTR_BAR_RELAXCONS_EQS,
    KTR_BAR_RELAXCONS_INEQS,
    KTR_BAR_RELAXCONS_ALL,
    KTR_MIP_METHOD_AUTO,
    KTR_MIP_METHOD_BB,
    KTR_MIP_METHOD_HQG,
    KTR_MIP_BRANCH_AUTO,
    KTR_MIP_BRANCH_MOSTFRAC,
    KTR_MIP_BRANCH_PSEUDOCOST,
    KTR_MIP_BRANCH_STRONG,
    KTR_MIP_SEL_AUTO,
    KTR_MIP_SEL_DEPTHFIRST,
    KTR_MIP_SEL_BESTBOUND,
    KTR_MIP_SEL_COMBO_1,
    KTR_MIP_OUTLEVEL_NONE,
    KTR_MIP_OUTLEVEL_ITERS,
    KTR_MIP_OUTLEVEL_ITERSTIME,
    KTR_MIP_OUTSUB_NONE,
    KTR_MIP_OUTSUB_YES,
    KTR_MIP_OUTSUB_YESPROB,
    KTR_MIP_DEBUG_NONE,
    KTR_MIP_DEBUG_ALL,
    KTR_MIP_IMPLICATNS_NO,
    KTR_MIP_IMPLICATNS_YES,
    KTR_MIP_GUB_BRANCH_NO,
    KTR_MIP_GUB_BRANCH_YES,
    KTR_MIP_KNAPSACK_NO,
    KTR_MIP_KNAPSACK_INEQ,
    KTR_MIP_KNAPSACK_INEQ_EQ,
    KTR_MIP_ROUND_AUTO,
    KTR_MIP_ROUND_NONE,
    KTR_MIP_ROUND_HEURISTIC,
    KTR_MIP_ROUND_NLP_SOME,
    KTR_MIP_ROUND_NLP_ALWAYS,
    KTR_MIP_ROOTALG_AUTO,
    KTR_MIP_ROOTALG_BAR_DIRECT,
    KTR_MIP_ROOTALG_BAR_CG,
    KTR_MIP_ROOTALG_ACT_CG,
    KTR_MIP_LPALG_AUTO,
    KTR_MIP_LPALG_BAR_DIRECT,
    KTR_MIP_LPALG_BAR_CG,
    KTR_MIP_LPALG_ACT_CG,
    KTR_MIP_TERMINATE_OPTIMAL,
    KTR_MIP_TERMINATE_FEASIBLE,
    KTR_MIP_HEURISTIC_AUTO,
    KTR_MIP_HEURISTIC_NONE,
    KTR_MIP_HEURISTIC_FEASPUMP,
    KTR_MIP_HEURISTIC_MPEC,
    KTR_MIP_PSEUDOINIT_AUTO,
    KTR_MIP_PSEUDOINIT_AVE,
    KTR_MIP_PSEUDOINIT_STRONG,
    KTR_PAR_CONCURRENT_EVALS_NO,
    KTR_PAR_CONCURRENT_EVALS_YES

const KTR_INFBOUND = @compat Float64(1.0e20)
const KTR_OBJGOAL_MINIMIZE = @compat Int32(0)
const KTR_OBJGOAL_MAXIMIZE = @compat Int32(1)
const KTR_OBJTYPE_GENERAL = @compat Int32(0)
const KTR_OBJTYPE_LINEAR = @compat Int32(1)
const KTR_OBJTYPE_QUADRATIC = @compat Int32(2)
const KTR_CONTYPE_GENERAL = @compat Int32(0)
const KTR_CONTYPE_LINEAR = @compat Int32(1)
const KTR_CONTYPE_QUADRATIC = @compat Int32(2)
const KTR_VARTYPE_CONTINUOUS = @compat Int32(0)
const KTR_VARTYPE_INTEGER = @compat Int32(1)
const KTR_VARTYPE_BINARY = @compat Int32(2)
const KTR_FNTYPE_UNCERTAIN = @compat Int32(0)
const KTR_FNTYPE_CONVEX = @compat Int32(1)
const KTR_FNTYPE_NONCONVEX = @compat Int32(2)
const KTR_RC_BEGINEND = @compat Int32(0)
const KTR_RC_EVALFC = @compat Int32(1)
const KTR_RC_EVALGA = @compat Int32(2)
const KTR_RC_EVALH = @compat Int32(3)
const KTR_RC_EVALX0 = @compat Int32(4)
const KTR_RC_FINISHED = @compat Int32(5)
const KTR_RC_NEWPOINT = @compat Int32(6)
const KTR_RC_EVALHV = @compat Int32(7)
const KTR_RC_EVALH_NO_F = @compat Int32(8)
const KTR_RC_EVALHV_NO_F = @compat Int32(9)
const KTR_RC_NODE = @compat Int32(10)
const KTR_RC_MSPROCESS = @compat Int32(11)
const KTR_RC_OPTIMAL = @compat Int32(0)
const KTR_RC_NEAR_OPT = @compat Int32(-100)
const KTR_RC_FEAS_XTOL = @compat Int32(-101)
const KTR_RC_FEAS_NO_IMPROVE = @compat Int32(-102)
const KTR_RC_FEAS_FTOL = @compat Int32(-103)
const KTR_RC_INFEASIBLE = @compat Int32(-200)
const KTR_RC_INFEAS_XTOL = @compat Int32(-201)
const KTR_RC_INFEAS_NO_IMPROVE = @compat Int32(-202)
const KTR_RC_INFEAS_MULTISTART = @compat Int32(-203)
const KTR_RC_INFEAS_CON_BOUNDS = @compat Int32(-204)
const KTR_RC_INFEAS_VAR_BOUNDS = @compat Int32(-205)
const KTR_RC_UNBOUNDED = @compat Int32(-300)
const KTR_RC_ITER_LIMIT = @compat Int32(-400)
const KTR_RC_TIME_LIMIT = @compat Int32(-401)
const KTR_RC_FEVAL_LIMIT = @compat Int32(-402)
const KTR_RC_MIP_EXH = @compat Int32(-403)
const KTR_RC_MIP_FEAS_TERM = @compat Int32(-404)
const KTR_RC_MIP_SOLVE_LIMIT = @compat Int32(-405)
const KTR_RC_MIP_NODE_LIMIT = @compat Int32(-406)
const KTR_RC_CALLBACK_ERR = @compat Int32(-500)
const KTR_RC_LP_SOLVER_ERR = @compat Int32(-501)
const KTR_RC_EVAL_ERR = @compat Int32(-502)
const KTR_RC_OUT_OF_MEMORY = @compat Int32(-503)
const KTR_RC_USER_TERMINATION = @compat Int32(-504)
const KTR_RC_OPEN_FILE_ERR = @compat Int32(-505)
const KTR_RC_BAD_N_OR_F = @compat Int32(-506)
const KTR_RC_BAD_CONSTRAINT = @compat Int32(-507)
const KTR_RC_BAD_JACOBIAN = @compat Int32(-508)
const KTR_RC_BAD_HESSIAN = @compat Int32(-509)
const KTR_RC_BAD_CON_INDEX = @compat Int32(-510)
const KTR_RC_BAD_JAC_INDEX = @compat Int32(-511)
const KTR_RC_BAD_HESS_INDEX = @compat Int32(-512)
const KTR_RC_BAD_CON_BOUNDS = @compat Int32(-513)
const KTR_RC_BAD_VAR_BOUNDS = @compat Int32(-514)
const KTR_RC_ILLEGAL_CALL = @compat Int32(-515)
const KTR_RC_BAD_KCPTR = @compat Int32(-516)
const KTR_RC_NULL_POINTER = @compat Int32(-517)
const KTR_RC_BAD_INIT_VALUE = @compat Int32(-518)
const KTR_RC_NEWPOINT_HALT = @compat Int32(-519)
const KTR_RC_BAD_LICENSE = @compat Int32(-520)
const KTR_RC_BAD_PARAMINPUT = @compat Int32(-521)
const KTR_RC_LINEAR_SOLVER_ERR = @compat Int32(-522)
const KTR_RC_INTERNAL_ERROR = @compat Int32(-600)
const KTR_PARAM_NEWPOINT = @compat Int32(1001)
const KTR_PARAM_HONORBNDS = @compat Int32(1002)
const KTR_PARAM_ALGORITHM = @compat Int32(1003)
const KTR_PARAM_ALG = @compat Int32(1003)
const KTR_PARAM_BAR_MURULE = @compat Int32(1004)
const KTR_PARAM_BARRULE = @compat Int32(1004)
const KTR_PARAM_BAR_FEASIBLE = @compat Int32(1006)
const KTR_PARAM_FEASIBLE = @compat Int32(1006)
const KTR_PARAM_GRADOPT = @compat Int32(1007)
const KTR_PARAM_HESSOPT = @compat Int32(1008)
const KTR_PARAM_BAR_INITPT = @compat Int32(1009)
const KTR_PARAM_LPSOLVER = @compat Int32(1012)
const KTR_PARAM_MAXCGIT = @compat Int32(1013)
const KTR_PARAM_MAXIT = @compat Int32(1014)
const KTR_PARAM_OUTLEV = @compat Int32(1015)
const KTR_PARAM_OUTMODE = @compat Int32(1016)
const KTR_PARAM_SCALE = @compat Int32(1017)
const KTR_PARAM_SHIFTINIT = @compat Int32(1018)
const KTR_PARAM_SOC = @compat Int32(1019)
const KTR_PARAM_DELTA = @compat Int32(1020)
const KTR_PARAM_BAR_FEASMODETOL = @compat Int32(1021)
const KTR_PARAM_FEASMODETOL = @compat Int32(1021)
const KTR_PARAM_FEASTOL = @compat Int32(1022)
const KTR_PARAM_FEASTOLABS = @compat Int32(1023)
const KTR_PARAM_MAXTIMECPU = @compat Int32(1024)
const KTR_PARAM_BAR_INITMU = @compat Int32(1025)
const KTR_PARAM_MU = @compat Int32(1025)
const KTR_PARAM_OBJRANGE = @compat Int32(1026)
const KTR_PARAM_OPTTOL = @compat Int32(1027)
const KTR_PARAM_OPTTOLABS = @compat Int32(1028)
const KTR_PARAM_PIVOT = @compat Int32(1029)
const KTR_PARAM_XTOL = @compat Int32(1030)
const KTR_PARAM_DEBUG = @compat Int32(1031)
const KTR_PARAM_MULTISTART = @compat Int32(1033)
const KTR_PARAM_MSMAXSOLVES = @compat Int32(1034)
const KTR_PARAM_MSMAXBNDRANGE = @compat Int32(1035)
const KTR_PARAM_MSMAXTIMECPU = @compat Int32(1036)
const KTR_PARAM_MSMAXTIMEREAL = @compat Int32(1037)
const KTR_PARAM_LMSIZE = @compat Int32(1038)
const KTR_PARAM_BAR_MAXCROSSIT = @compat Int32(1039)
const KTR_PARAM_MAXCROSSIT = @compat Int32(1039)
const KTR_PARAM_MAXTIMEREAL = @compat Int32(1040)
const KTR_PARAM_PRECOND = @compat Int32(1041)
const KTR_PARAM_BLASOPTION = @compat Int32(1042)
const KTR_PARAM_BAR_MAXREFACTOR = @compat Int32(1043)
const KTR_PARAM_BAR_MAXBACKTRACK = @compat Int32(1044)
const KTR_PARAM_BLASOPTIONLIB = @compat Int32(1045)
const KTR_PARAM_OUTAPPEND = @compat Int32(1046)
const KTR_PARAM_OUTDIR = @compat Int32(1047)
const KTR_PARAM_CPLEXLIB = @compat Int32(1048)
const KTR_PARAM_BAR_PENRULE = @compat Int32(1049)
const KTR_PARAM_BAR_PENCONS = @compat Int32(1050)
const KTR_PARAM_MSNUMTOSAVE = @compat Int32(1051)
const KTR_PARAM_MSSAVETOL = @compat Int32(1052)
const KTR_PARAM_PRESOLVEDEBUG = @compat Int32(1053)
const KTR_PARAM_MSTERMINATE = @compat Int32(1054)
const KTR_PARAM_MSSTARTPTRANGE = @compat Int32(1055)
const KTR_PARAM_INFEASTOL = @compat Int32(1056)
const KTR_PARAM_LINSOLVER = @compat Int32(1057)
const KTR_PARAM_BAR_DIRECTINTERVAL = @compat Int32(1058)
const KTR_PARAM_PRESOLVE = @compat Int32(1059)
const KTR_PARAM_PRESOLVE_TOL = @compat Int32(1060)
const KTR_PARAM_BAR_SWITCHRULE = @compat Int32(1061)
const KTR_PARAM_HESSIAN_NO_F = @compat Int32(1062)
const KTR_PARAM_MA_TERMINATE = @compat Int32(1063)
const KTR_PARAM_MA_MAXTIMECPU = @compat Int32(1064)
const KTR_PARAM_MA_MAXTIMEREAL = @compat Int32(1065)
const KTR_PARAM_MSSEED = @compat Int32(1066)
const KTR_PARAM_MA_OUTSUB = @compat Int32(1067)
const KTR_PARAM_MS_OUTSUB = @compat Int32(1068)
const KTR_PARAM_XPRESSLIB = @compat Int32(1069)
const KTR_PARAM_TUNER = @compat Int32(1070)
const KTR_PARAM_TUNER_OPTIONSFILE = @compat Int32(1071)
const KTR_PARAM_TUNER_MAXTIMECPU = @compat Int32(1072)
const KTR_PARAM_TUNER_MAXTIMEREAL = @compat Int32(1073)
const KTR_PARAM_TUNER_OUTSUB = @compat Int32(1074)
const KTR_PARAM_TUNER_TERMINATE = @compat Int32(1075)
const KTR_PARAM_LINSOLVER_OOC = @compat Int32(1076)
const KTR_PARAM_BAR_RELAXCONS = @compat Int32(1077)
const KTR_PARAM_MIP_METHOD = @compat Int32(2001)
const KTR_PARAM_MIP_BRANCHRULE = @compat Int32(2002)
const KTR_PARAM_MIP_SELECTRULE = @compat Int32(2003)
const KTR_PARAM_MIP_INTGAPABS = @compat Int32(2004)
const KTR_PARAM_MIP_INTGAPREL = @compat Int32(2005)
const KTR_PARAM_MIP_MAXTIMECPU = @compat Int32(2006)
const KTR_PARAM_MIP_MAXTIMEREAL = @compat Int32(2007)
const KTR_PARAM_MIP_MAXSOLVES = @compat Int32(2008)
const KTR_PARAM_MIP_INTEGERTOL = @compat Int32(2009)
const KTR_PARAM_MIP_OUTLEVEL = @compat Int32(2010)
const KTR_PARAM_MIP_OUTINTERVAL = @compat Int32(2011)
const KTR_PARAM_MIP_OUTSUB = @compat Int32(2012)
const KTR_PARAM_MIP_DEBUG = @compat Int32(2013)
const KTR_PARAM_MIP_IMPLICATNS = @compat Int32(2014)
const KTR_PARAM_MIP_GUB_BRANCH = @compat Int32(2015)
const KTR_PARAM_MIP_KNAPSACK = @compat Int32(2016)
const KTR_PARAM_MIP_ROUNDING = @compat Int32(2017)
const KTR_PARAM_MIP_ROOTALG = @compat Int32(2018)
const KTR_PARAM_MIP_LPALG = @compat Int32(2019)
const KTR_PARAM_MIP_TERMINATE = @compat Int32(2020)
const KTR_PARAM_MIP_MAXNODES = @compat Int32(2021)
const KTR_PARAM_MIP_HEURISTIC = @compat Int32(2022)
const KTR_PARAM_MIP_HEUR_MAXIT = @compat Int32(2023)
const KTR_PARAM_MIP_HEUR_MAXTIMECPU = @compat Int32(2024)
const KTR_PARAM_MIP_HEUR_MAXTIMEREAL = @compat Int32(2025)
const KTR_PARAM_MIP_PSEUDOINIT = @compat Int32(2026)
const KTR_PARAM_MIP_STRONG_MAXIT = @compat Int32(2027)
const KTR_PARAM_MIP_STRONG_CANDLIM = @compat Int32(2028)
const KTR_PARAM_MIP_STRONG_LEVEL = @compat Int32(2029)
const KTR_PARAM_PAR_NUMTHREADS = @compat Int32(3001)
const KTR_PARAM_PAR_CONCURRENT_EVALS = @compat Int32(3002)
const KTR_PARAM_PAR_BLASNUMTHREADS = @compat Int32(3003)
const KTR_PARAM_PAR_LSNUMTHREADS = @compat Int32(3004)

const KTR_NEWPOINT_NONE = @compat Int32(0)
const KTR_NEWPOINT_SAVEONE = @compat Int32(1)
const KTR_NEWPOINT_SAVEALL = @compat Int32(2)
const KTR_NEWPOINT_USER = @compat Int32(3)
const KTR_HONORBNDS_NO = @compat Int32(0)
const KTR_HONORBNDS_ALWAYS = @compat Int32(1)
const KTR_HONORBNDS_INITPT = @compat Int32(2)
const KTR_ALG_AUTOMATIC = @compat Int32(0)
const KTR_ALG_AUTO = @compat Int32(0)
const KTR_ALG_BAR_DIRECT = @compat Int32(1)
const KTR_ALG_BAR_CG = @compat Int32(2)
const KTR_ALG_ACT_CG = @compat Int32(3)
const KTR_ALG_IPDIRECT = @compat Int32(1)
const KTR_ALG_IPCG = @compat Int32(2)
const KTR_ALG_ACTIVE = @compat Int32(3)
const KTR_ALG_MULTI = @compat Int32(5)
const KTR_BAR_MURULE_AUTOMATIC = @compat Int32(0)
const KTR_BAR_MURULE_AUTO = @compat Int32(0)
const KTR_BAR_MURULE_MONOTONE = @compat Int32(1)
const KTR_BAR_MURULE_ADAPTIVE = @compat Int32(2)
const KTR_BAR_MURULE_PROBING = @compat Int32(3)
const KTR_BAR_MURULE_DAMPMPC = @compat Int32(4)
const KTR_BAR_MURULE_FULLMPC = @compat Int32(5)
const KTR_BAR_MURULE_QUALITY = @compat Int32(6)
const KTR_BAR_FEASIBLE_NO = @compat Int32(0)
const KTR_BAR_FEASIBLE_STAY = @compat Int32(1)
const KTR_BAR_FEASIBLE_GET = @compat Int32(2)
const KTR_BAR_FEASIBLE_GET_STAY = @compat Int32(3)
const KTR_FEASIBLE_NO = @compat Int32(0)
const KTR_FEASIBLE_ALWAYS = @compat Int32(1)
const KTR_GRADOPT_EXACT = @compat Int32(1)
const KTR_GRADOPT_FORWARD = @compat Int32(2)
const KTR_GRADOPT_CENTRAL = @compat Int32(3)
const KTR_GRADOPT_USER_FORWARD = @compat Int32(4)
const KTR_GRADOPT_USER_CENTRAL = @compat Int32(5)
const KTR_HESSOPT_EXACT = @compat Int32(1)
const KTR_HESSOPT_BFGS = @compat Int32(2)
const KTR_HESSOPT_SR1 = @compat Int32(3)
const KTR_HESSOPT_FINITE_DIFF = @compat Int32(4)
const KTR_HESSOPT_PRODUCT = @compat Int32(5)
const KTR_HESSOPT_LBFGS = @compat Int32(6)
const KTR_BAR_INITPT_AUTO = @compat Int32(0)
const KTR_BAR_INITPT_YES = @compat Int32(1)
const KTR_BAR_INITPT_STRAT1 = @compat Int32(1)
const KTR_BAR_INITPT_NO = @compat Int32(2)
const KTR_BAR_INITPT_STRAT2 = @compat Int32(2)
const KTR_BAR_INITPT_STRAT3 = @compat Int32(3)
const KTR_LP_INTERNAL = @compat Int32(1)
const KTR_LP_CPLEX = @compat Int32(2)
const KTR_LP_XPRESS = @compat Int32(3)
const KTR_OUTLEV_NONE = @compat Int32(0)
const KTR_OUTLEV_SUMMARY = @compat Int32(1)
const KTR_OUTLEV_MAJORIT10 = @compat Int32(2)
const KTR_OUTLEV_ITER_10 = @compat Int32(2)
const KTR_OUTLEV_MAJORIT = @compat Int32(3)
const KTR_OUTLEV_ITER = @compat Int32(3)
const KTR_OUTLEV_ALLIT = @compat Int32(4)
const KTR_OUTLEV_ITER_VERBOSE = @compat Int32(4)
const KTR_OUTLEV_ALLIT_X = @compat Int32(5)
const KTR_OUTLEV_ITER_X = @compat Int32(5)
const KTR_OUTLEV_ALL = @compat Int32(6)
const KTR_OUTMODE_SCREEN = @compat Int32(0)
const KTR_OUTMODE_FILE = @compat Int32(1)
const KTR_OUTMODE_BOTH = @compat Int32(2)
const KTR_SCALE_NEVER = @compat Int32(0)
const KTR_SCALE_ALLOW = @compat Int32(1)
const KTR_SOC_NO = @compat Int32(0)
const KTR_SOC_MAYBE = @compat Int32(1)
const KTR_SOC_YES = @compat Int32(2)
const KTR_DEBUG_NONE = @compat Int32(0)
const KTR_DEBUG_PROBLEM = @compat Int32(1)
const KTR_DEBUG_EXECUTION = @compat Int32(2)
const KTR_MULTISTART_NO = @compat Int32(0)
const KTR_MULTISTART_YES = @compat Int32(1)
const KTR_PRECOND_NONE = @compat Int32(0)
const KTR_PRECOND_CHOL = @compat Int32(1)
const KTR_BLASOPTION_KNITRO = @compat Int32(0)
const KTR_BLASOPTION_INTEL = @compat Int32(1)
const KTR_BLASOPTION_DYNAMIC = @compat Int32(2)
const KTR_OUTAPPEND_NO = @compat Int32(0)
const KTR_OUTAPPEND_YES = @compat Int32(1)
const KTR_BAR_PENRULE_AUTO = @compat Int32(0)
const KTR_BAR_PENRULE_SINGLE = @compat Int32(1)
const KTR_BAR_PENRULE_FLEX = @compat Int32(2)
const KTR_BAR_PENCONS_AUTO = @compat Int32(0)
const KTR_BAR_PENCONS_NONE = @compat Int32(1)
const KTR_BAR_PENCONS_ALL = @compat Int32(2)
const KTR_BAR_PENCONS_EQUALITIES = @compat Int32(3)
const KTR_BAR_PENCONS_INFEAS = @compat Int32(4)
const KTR_PRESOLVEDBG_NONE = @compat Int32(0)
const KTR_PRESOLVEDBG_BASIC = @compat Int32(1)
const KTR_PRESOLVEDBG_VERBOSE = @compat Int32(2)
const KTR_MSTERMINATE_MAXSOLVES = @compat Int32(0)
const KTR_MSTERMINATE_OPTIMAL = @compat Int32(1)
const KTR_MSTERMINATE_FEASIBLE = @compat Int32(2)
const KTR_LINSOLVER_AUTO = @compat Int32(0)
const KTR_LINSOLVER_INTERNAL = @compat Int32(1)
const KTR_LINSOLVER_HYBRID = @compat Int32(2)
const KTR_LINSOLVER_DENSEQR = @compat Int32(3)
const KTR_LINSOLVER_MA27 = @compat Int32(4)
const KTR_LINSOLVER_MA57 = @compat Int32(5)
const KTR_LINSOLVER_MKLPARDISO = @compat Int32(6)
const KTR_PRESOLVE_NONE = @compat Int32(0)
const KTR_PRESOLVE_BASIC = @compat Int32(1)
const KTR_PRESOLVE_ADVANCED = @compat Int32(2)
const KTR_BAR_SWITCHRULE_AUTO = @compat Int32(0)
const KTR_BAR_SWITCHRULE_NEVER = @compat Int32(1)
const KTR_BAR_SWITCHRULE_LEVEL1 = @compat Int32(2)
const KTR_BAR_SWITCHRULE_LEVEL2 = @compat Int32(3)
const KTR_HESSIAN_NO_F_FORBID = @compat Int32(0)
const KTR_HESSIAN_NO_F_ALLOW = @compat Int32(1)
const KTR_MA_TERMINATE_ALL = @compat Int32(0)
const KTR_MA_TERMINATE_OPTIMAL = @compat Int32(1)
const KTR_MA_TERMINATE_FEASIBLE = @compat Int32(2)
const KTR_MA_OUTSUB_NONE = @compat Int32(0)
const KTR_MA_OUTSUB_YES = @compat Int32(1)
const KTR_MS_OUTSUB_NONE = @compat Int32(0)
const KTR_MS_OUTSUB_YES = @compat Int32(1)
const KTR_TUNER_OFF = @compat Int32(0)
const KTR_TUNER_ON = @compat Int32(1)
const KTR_TUNER_OUTSUB_NONE = @compat Int32(0)
const KTR_TUNER_OUTSUB_YES = @compat Int32(1)
const KTR_TUNER_OUTSUB_SUMMARY = @compat Int32(1)
const KTR_TUNER_OUTSUB_ALL = @compat Int32(2)
const KTR_TUNER_TERMINATE_ALL = @compat Int32(0)
const KTR_TUNER_TERMINATE_OPTIMAL = @compat Int32(1)
const KTR_TUNER_TERMINATE_FEASIBLE = @compat Int32(2)
const KTR_LINSOLVER_OOC_NO = @compat Int32(0)
const KTR_LINSOLVER_OOC_MAYBE = @compat Int32(1)
const KTR_LINSOLVER_OOC_YES = @compat Int32(2)
const KTR_BAR_RELAXCONS_NONE = @compat Int32(0)
const KTR_BAR_RELAXCONS_EQS = @compat Int32(1)
const KTR_BAR_RELAXCONS_INEQS = @compat Int32(2)
const KTR_BAR_RELAXCONS_ALL = @compat Int32(3)
const KTR_MIP_METHOD_AUTO = @compat Int32(0)
const KTR_MIP_METHOD_BB = @compat Int32(1)
const KTR_MIP_METHOD_HQG = @compat Int32(2)
const KTR_MIP_BRANCH_AUTO = @compat Int32(0)
const KTR_MIP_BRANCH_MOSTFRAC = @compat Int32(1)
const KTR_MIP_BRANCH_PSEUDOCOST = @compat Int32(2)
const KTR_MIP_BRANCH_STRONG = @compat Int32(3)
const KTR_MIP_SEL_AUTO = @compat Int32(0)
const KTR_MIP_SEL_DEPTHFIRST = @compat Int32(1)
const KTR_MIP_SEL_BESTBOUND = @compat Int32(2)
const KTR_MIP_SEL_COMBO_1 = @compat Int32(3)
const KTR_MIP_OUTLEVEL_NONE = @compat Int32(0)
const KTR_MIP_OUTLEVEL_ITERS = @compat Int32(1)
const KTR_MIP_OUTLEVEL_ITERSTIME = @compat Int32(2)
const KTR_MIP_OUTSUB_NONE = @compat Int32(0)
const KTR_MIP_OUTSUB_YES = @compat Int32(1)
const KTR_MIP_OUTSUB_YESPROB = @compat Int32(2)
const KTR_MIP_DEBUG_NONE = @compat Int32(0)
const KTR_MIP_DEBUG_ALL = @compat Int32(1)
const KTR_MIP_IMPLICATNS_NO = @compat Int32(0)
const KTR_MIP_IMPLICATNS_YES = @compat Int32(1)
const KTR_MIP_GUB_BRANCH_NO = @compat Int32(0)
const KTR_MIP_GUB_BRANCH_YES = @compat Int32(1)
const KTR_MIP_KNAPSACK_NO = @compat Int32(0)
const KTR_MIP_KNAPSACK_INEQ = @compat Int32(1)
const KTR_MIP_KNAPSACK_INEQ_EQ = @compat Int32(2)
const KTR_MIP_ROUND_AUTO = @compat Int32(0)
const KTR_MIP_ROUND_NONE = @compat Int32(1)
const KTR_MIP_ROUND_HEURISTIC = @compat Int32(2)
const KTR_MIP_ROUND_NLP_SOME = @compat Int32(3)
const KTR_MIP_ROUND_NLP_ALWAYS = @compat Int32(4)
const KTR_MIP_ROOTALG_AUTO = @compat Int32(0)
const KTR_MIP_ROOTALG_BAR_DIRECT = @compat Int32(1)
const KTR_MIP_ROOTALG_BAR_CG = @compat Int32(2)
const KTR_MIP_ROOTALG_ACT_CG = @compat Int32(3)
const KTR_MIP_LPALG_AUTO = @compat Int32(0)
const KTR_MIP_LPALG_BAR_DIRECT = @compat Int32(1)
const KTR_MIP_LPALG_BAR_CG = @compat Int32(2)
const KTR_MIP_LPALG_ACT_CG = @compat Int32(3)
const KTR_MIP_TERMINATE_OPTIMAL = @compat Int32(0)
const KTR_MIP_TERMINATE_FEASIBLE = @compat Int32(1)
const KTR_MIP_HEURISTIC_AUTO = @compat Int32(0)
const KTR_MIP_HEURISTIC_NONE = @compat Int32(1)
const KTR_MIP_HEURISTIC_FEASPUMP = @compat Int32(2)
const KTR_MIP_HEURISTIC_MPEC = @compat Int32(3)
const KTR_MIP_PSEUDOINIT_AUTO = @compat Int32(0)
const KTR_MIP_PSEUDOINIT_AVE = @compat Int32(1)
const KTR_MIP_PSEUDOINIT_STRONG = @compat Int32(2)
const KTR_PAR_CONCURRENT_EVALS_NO = @compat Int32(0)
const KTR_PAR_CONCURRENT_EVALS_YES = @compat Int32(1)
