export
    KTR_INFBOUND,
    KTR_OBJGOAL_MINIMIZE,
    KTR_OBJGOAL_MAXIMIZE,
    KTR_OBJTYPE_GENERAL,
    KTR_OBJTYPE_LINEAR,
    KTR_OBJTYPE_QUADRATIC,
    KTR_CONTYPE_GENERAL,
    KTR_CONTYPE_LINEAR,
    KTR_CONTYPE_QUADRATIC,
    KTR_VARTYPE_CONTINUOUS,
    KTR_VARTYPE_INTEGER,
    KTR_VARTYPE_BINARY,
    KTR_FNTYPE_UNCERTAIN,
    KTR_FNTYPE_CONVEX,
    KTR_FNTYPE_NONCONVEX,
    KTR_RC_BEGINEND,
    KTR_RC_EVALFC,
    KTR_RC_EVALGA,
    KTR_RC_EVALH,
    KTR_RC_EVALX0,
    KTR_RC_FINISHED,
    KTR_RC_NEWPOINT,
    KTR_RC_EVALHV,
    KTR_RC_EVALH_NO_F,
    KTR_RC_EVALHV_NO_F,
    KTR_RC_NODE,
    KTR_RC_MSPROCESS,
    KTR_RC_OPTIMAL,
    KTR_RC_NEAR_OPT,
    KTR_RC_FEAS_XTOL,
    KTR_RC_FEAS_NO_IMPROVE,
    KTR_RC_FEAS_FTOL,
    KTR_RC_INFEASIBLE,
    KTR_RC_INFEAS_XTOL,
    KTR_RC_INFEAS_NO_IMPROVE,
    KTR_RC_INFEAS_MULTISTART,
    KTR_RC_INFEAS_CON_BOUNDS,
    KTR_RC_INFEAS_VAR_BOUNDS,
    KTR_RC_UNBOUNDED,
    KTR_RC_ITER_LIMIT,
    KTR_RC_TIME_LIMIT,
    KTR_RC_FEVAL_LIMIT,
    KTR_RC_MIP_EXH,
    KTR_RC_MIP_FEAS_TERM,
    KTR_RC_MIP_SOLVE_LIMIT,
    KTR_RC_MIP_NODE_LIMIT,
    KTR_RC_CALLBACK_ERR,
    KTR_RC_LP_SOLVER_ERR,
    KTR_RC_EVAL_ERR,
    KTR_RC_OUT_OF_MEMORY,
    KTR_RC_USER_TERMINATION,
    KTR_RC_OPEN_FILE_ERR,
    KTR_RC_BAD_N_OR_F,
    KTR_RC_BAD_CONSTRAINT,
    KTR_RC_BAD_JACOBIAN,
    KTR_RC_BAD_HESSIAN,
    KTR_RC_BAD_CON_INDEX,
    KTR_RC_BAD_JAC_INDEX,
    KTR_RC_BAD_HESS_INDEX,
    KTR_RC_BAD_CON_BOUNDS,
    KTR_RC_BAD_VAR_BOUNDS,
    KTR_RC_ILLEGAL_CALL,
    KTR_RC_BAD_KCPTR,
    KTR_RC_NULL_POINTER,
    KTR_RC_BAD_INIT_VALUE,
    KTR_RC_NEWPOINT_HALT,
    KTR_RC_BAD_LICENSE,
    KTR_RC_BAD_PARAMINPUT,
    KTR_RC_LINEAR_SOLVER_ERR,
    KTR_RC_INTERNAL_ERROR,
    KTR_PARAM_NEWPOINT,
    KTR_PARAM_HONORBNDS,
    KTR_PARAM_ALGORITHM,
    KTR_PARAM_ALG,
    KTR_PARAM_BAR_MURULE,
    KTR_PARAM_BARRULE,
    KTR_PARAM_BAR_FEASIBLE,
    KTR_PARAM_FEASIBLE,
    KTR_PARAM_GRADOPT,
    KTR_PARAM_HESSOPT,
    KTR_PARAM_BAR_INITPT,
    KTR_PARAM_LPSOLVER,
    KTR_PARAM_MAXCGIT,
    KTR_PARAM_MAXIT,
    KTR_PARAM_OUTLEV,
    KTR_PARAM_OUTMODE,
    KTR_PARAM_SCALE,
    KTR_PARAM_SHIFTINIT,
    KTR_PARAM_SOC,
    KTR_PARAM_DELTA,
    KTR_PARAM_BAR_FEASMODETOL,
    KTR_PARAM_FEASMODETOL,
    KTR_PARAM_FEASTOL,
    KTR_PARAM_FEASTOLABS,
    KTR_PARAM_MAXTIMECPU,
    KTR_PARAM_BAR_INITMU,
    KTR_PARAM_MU,
    KTR_PARAM_OBJRANGE,
    KTR_PARAM_OPTTOL,
    KTR_PARAM_OPTTOLABS,
    KTR_PARAM_PIVOT,
    KTR_PARAM_XTOL,
    KTR_PARAM_DEBUG,
    KTR_PARAM_MULTISTART,
    KTR_PARAM_MSMAXSOLVES,
    KTR_PARAM_MSMAXBNDRANGE,
    KTR_PARAM_MSMAXTIMECPU,
    KTR_PARAM_MSMAXTIMEREAL,
    KTR_PARAM_LMSIZE,
    KTR_PARAM_BAR_MAXCROSSIT,
    KTR_PARAM_MAXCROSSIT,
    KTR_PARAM_MAXTIMEREAL,
    KTR_PARAM_PRECOND,
    KTR_PARAM_BLASOPTION,
    KTR_PARAM_BAR_MAXREFACTOR,
    KTR_PARAM_BAR_MAXBACKTRACK,
    KTR_PARAM_BLASOPTIONLIB,
    KTR_PARAM_OUTAPPEND,
    KTR_PARAM_OUTDIR,
    KTR_PARAM_CPLEXLIB,
    KTR_PARAM_BAR_PENRULE,
    KTR_PARAM_BAR_PENCONS,
    KTR_PARAM_MSNUMTOSAVE,
    KTR_PARAM_MSSAVETOL,
    KTR_PARAM_PRESOLVEDEBUG,
    KTR_PARAM_MSTERMINATE,
    KTR_PARAM_MSSTARTPTRANGE,
    KTR_PARAM_INFEASTOL,
    KTR_PARAM_LINSOLVER,
    KTR_PARAM_BAR_DIRECTINTERVAL,
    KTR_PARAM_PRESOLVE,
    KTR_PARAM_PRESOLVE_TOL,
    KTR_PARAM_BAR_SWITCHRULE,
    KTR_PARAM_HESSIAN_NO_F,
    KTR_PARAM_MA_TERMINATE,
    KTR_PARAM_MA_MAXTIMECPU,
    KTR_PARAM_MA_MAXTIMEREAL,
    KTR_PARAM_MSSEED,
    KTR_PARAM_MA_OUTSUB,
    KTR_PARAM_MS_OUTSUB,
    KTR_PARAM_XPRESSLIB,
    KTR_PARAM_TUNER,
    KTR_PARAM_TUNER_OPTIONSFILE,
    KTR_PARAM_TUNER_MAXTIMECPU,
    KTR_PARAM_TUNER_MAXTIMEREAL,
    KTR_PARAM_TUNER_OUTSUB,
    KTR_PARAM_TUNER_TERMINATE,
    KTR_PARAM_LINSOLVER_OOC,
    KTR_PARAM_BAR_RELAXCONS,
    KTR_PARAM_MIP_METHOD,
    KTR_PARAM_MIP_BRANCHRULE,
    KTR_PARAM_MIP_SELECTRULE,
    KTR_PARAM_MIP_INTGAPABS,
    KTR_PARAM_MIP_INTGAPREL,
    KTR_PARAM_MIP_MAXTIMECPU,
    KTR_PARAM_MIP_MAXTIMEREAL,
    KTR_PARAM_MIP_MAXSOLVES,
    KTR_PARAM_MIP_INTEGERTOL,
    KTR_PARAM_MIP_OUTLEVEL,
    KTR_PARAM_MIP_OUTINTERVAL,
    KTR_PARAM_MIP_OUTSUB,
    KTR_PARAM_MIP_DEBUG,
    KTR_PARAM_MIP_IMPLICATNS,
    KTR_PARAM_MIP_GUB_BRANCH,
    KTR_PARAM_MIP_KNAPSACK,
    KTR_PARAM_MIP_ROUNDING,
    KTR_PARAM_MIP_ROOTALG,
    KTR_PARAM_MIP_LPALG,
    KTR_PARAM_MIP_TERMINATE,
    KTR_PARAM_MIP_MAXNODES,
    KTR_PARAM_MIP_HEURISTIC,
    KTR_PARAM_MIP_HEUR_MAXIT,
    KTR_PARAM_MIP_HEUR_MAXTIMECPU,
    KTR_PARAM_MIP_HEUR_MAXTIMEREAL,
    KTR_PARAM_MIP_PSEUDOINIT,
    KTR_PARAM_MIP_STRONG_MAXIT,
    KTR_PARAM_MIP_STRONG_CANDLIM,
    KTR_PARAM_MIP_STRONG_LEVEL,
    KTR_PARAM_PAR_NUMTHREADS,
    KTR_PARAM_PAR_CONCURRENT_EVALS,
    KTR_PARAM_PAR_BLASNUMTHREADS,
    KTR_PARAM_PAR_LSNUMTHREADS,
    KTR_NEWPOINT_NONE,
    KTR_NEWPOINT_SAVEONE,
    KTR_NEWPOINT_SAVEALL,
    KTR_NEWPOINT_USER,
    KTR_HONORBNDS_NO,
    KTR_HONORBNDS_ALWAYS,
    KTR_HONORBNDS_INITPT,
    KTR_ALG_AUTOMATIC,
    KTR_ALG_AUTO,
    KTR_ALG_BAR_DIRECT,
    KTR_ALG_BAR_CG,
    KTR_ALG_ACT_CG,
    KTR_ALG_IPDIRECT,
    KTR_ALG_IPCG,
    KTR_ALG_ACTIVE,
    KTR_ALG_MULTI,
    KTR_BAR_MURULE_AUTOMATIC,
    KTR_BAR_MURULE_AUTO,
    KTR_BAR_MURULE_MONOTONE,
    KTR_BAR_MURULE_ADAPTIVE,
    KTR_BAR_MURULE_PROBING,
    KTR_BAR_MURULE_DAMPMPC,
    KTR_BAR_MURULE_FULLMPC,
    KTR_BAR_MURULE_QUALITY,
    KTR_BAR_FEASIBLE_NO,
    KTR_BAR_FEASIBLE_STAY,
    KTR_BAR_FEASIBLE_GET,
    KTR_BAR_FEASIBLE_GET_STAY,
    KTR_FEASIBLE_NO,
    KTR_FEASIBLE_ALWAYS,
    KTR_GRADOPT_EXACT,
    KTR_GRADOPT_FORWARD,
    KTR_GRADOPT_CENTRAL,
    KTR_GRADOPT_USER_FORWARD,
    KTR_GRADOPT_USER_CENTRAL,
    KTR_HESSOPT_EXACT,
    KTR_HESSOPT_BFGS,
    KTR_HESSOPT_SR1,
    KTR_HESSOPT_FINITE_DIFF,
    KTR_HESSOPT_PRODUCT,
    KTR_HESSOPT_LBFGS,
    KTR_BAR_INITPT_AUTO,
    KTR_BAR_INITPT_YES,
    KTR_BAR_INITPT_STRAT1,
    KTR_BAR_INITPT_NO,
    KTR_BAR_INITPT_STRAT2,
    KTR_BAR_INITPT_STRAT3,
    KTR_LP_INTERNAL,
    KTR_LP_CPLEX,
    KTR_LP_XPRESS,
    KTR_OUTLEV_NONE,
    KTR_OUTLEV_SUMMARY,
    KTR_OUTLEV_MAJORIT10,
    KTR_OUTLEV_ITER_10,
    KTR_OUTLEV_MAJORIT,
    KTR_OUTLEV_ITER,
    KTR_OUTLEV_ALLIT,
    KTR_OUTLEV_ITER_VERBOSE,
    KTR_OUTLEV_ALLIT_X,
    KTR_OUTLEV_ITER_X,
    KTR_OUTLEV_ALL,
    KTR_OUTMODE_SCREEN,
    KTR_OUTMODE_FILE,
    KTR_OUTMODE_BOTH,
    KTR_SCALE_NEVER,
    KTR_SCALE_ALLOW,
    KTR_SOC_NO,
    KTR_SOC_MAYBE,
    KTR_SOC_YES,
    KTR_DEBUG_NONE,
    KTR_DEBUG_PROBLEM,
    KTR_DEBUG_EXECUTION,
    KTR_MULTISTART_NO,
    KTR_MULTISTART_YES,
    KTR_PRECOND_NONE,
    KTR_PRECOND_CHOL,
    KTR_BLASOPTION_KNITRO,
    KTR_BLASOPTION_INTEL,
    KTR_BLASOPTION_DYNAMIC,
    KTR_OUTAPPEND_NO,
    KTR_OUTAPPEND_YES,
    KTR_BAR_PENRULE_AUTO,
    KTR_BAR_PENRULE_SINGLE,
    KTR_BAR_PENRULE_FLEX,
    KTR_BAR_PENCONS_AUTO,
    KTR_BAR_PENCONS_NONE,
    KTR_BAR_PENCONS_ALL,
    KTR_BAR_PENCONS_EQUALITIES,
    KTR_BAR_PENCONS_INFEAS,
    KTR_PRESOLVEDBG_NONE,
    KTR_PRESOLVEDBG_BASIC,
    KTR_PRESOLVEDBG_VERBOSE,
    KTR_MSTERMINATE_MAXSOLVES,
    KTR_MSTERMINATE_OPTIMAL,
    KTR_MSTERMINATE_FEASIBLE,
    KTR_LINSOLVER_AUTO,
    KTR_LINSOLVER_INTERNAL,
    KTR_LINSOLVER_HYBRID,
    KTR_LINSOLVER_DENSEQR,
    KTR_LINSOLVER_MA27,
    KTR_LINSOLVER_MA57,
    KTR_LINSOLVER_MKLPARDISO,
    KTR_PRESOLVE_NONE,
    KTR_PRESOLVE_BASIC,
    KTR_PRESOLVE_ADVANCED,
    KTR_BAR_SWITCHRULE_AUTO,
    KTR_BAR_SWITCHRULE_NEVER,
    KTR_BAR_SWITCHRULE_LEVEL1,
    KTR_BAR_SWITCHRULE_LEVEL2,
    KTR_HESSIAN_NO_F_FORBID,
    KTR_HESSIAN_NO_F_ALLOW,
    KTR_MA_TERMINATE_ALL,
    KTR_MA_TERMINATE_OPTIMAL,
    KTR_MA_TERMINATE_FEASIBLE,
    KTR_MA_OUTSUB_NONE,
    KTR_MA_OUTSUB_YES,
    KTR_MS_OUTSUB_NONE,
    KTR_MS_OUTSUB_YES,
    KTR_TUNER_OFF,
    KTR_TUNER_ON,
    KTR_TUNER_OUTSUB_NONE,
    KTR_TUNER_OUTSUB_YES,
    KTR_TUNER_OUTSUB_SUMMARY,
    KTR_TUNER_OUTSUB_ALL,
    KTR_TUNER_TERMINATE_ALL,
    KTR_TUNER_TERMINATE_OPTIMAL,
    KTR_TUNER_TERMINATE_FEASIBLE,
    KTR_LINSOLVER_OOC_NO,
    KTR_LINSOLVER_OOC_MAYBE,
    KTR_LINSOLVER_OOC_YES,
    KTR_BAR_RELAXCONS_NONE,
    KTR_BAR_RELAXCONS_EQS,
    KTR_BAR_RELAXCONS_INEQS,
    KTR_BAR_RELAXCONS_ALL,
    KTR_MIP_METHOD_AUTO,
    KTR_MIP_METHOD_BB,
    KTR_MIP_METHOD_HQG,
    KTR_MIP_BRANCH_AUTO,
    KTR_MIP_BRANCH_MOSTFRAC,
    KTR_MIP_BRANCH_PSEUDOCOST,
    KTR_MIP_BRANCH_STRONG,
    KTR_MIP_SEL_AUTO,
    KTR_MIP_SEL_DEPTHFIRST,
    KTR_MIP_SEL_BESTBOUND,
    KTR_MIP_SEL_COMBO_1,
    KTR_MIP_OUTLEVEL_NONE,
    KTR_MIP_OUTLEVEL_ITERS,
    KTR_MIP_OUTLEVEL_ITERSTIME,
    KTR_MIP_OUTSUB_NONE,
    KTR_MIP_OUTSUB_YES,
    KTR_MIP_OUTSUB_YESPROB,
    KTR_MIP_DEBUG_NONE,
    KTR_MIP_DEBUG_ALL,
    KTR_MIP_IMPLICATNS_NO,
    KTR_MIP_IMPLICATNS_YES,
    KTR_MIP_GUB_BRANCH_NO,
    KTR_MIP_GUB_BRANCH_YES,
    KTR_MIP_KNAPSACK_NO,
    KTR_MIP_KNAPSACK_INEQ,
    KTR_MIP_KNAPSACK_INEQ_EQ,
    KTR_MIP_ROUND_AUTO,
    KTR_MIP_ROUND_NONE,
    KTR_MIP_ROUND_HEURISTIC,
    KTR_MIP_ROUND_NLP_SOME,
    KTR_MIP_ROUND_NLP_ALWAYS,
    KTR_MIP_ROOTALG_AUTO,
    KTR_MIP_ROOTALG_BAR_DIRECT,
    KTR_MIP_ROOTALG_BAR_CG,
    KTR_MIP_ROOTALG_ACT_CG,
    KTR_MIP_LPALG_AUTO,
    KTR_MIP_LPALG_BAR_DIRECT,
    KTR_MIP_LPALG_BAR_CG,
    KTR_MIP_LPALG_ACT_CG,
    KTR_MIP_TERMINATE_OPTIMAL,
    KTR_MIP_TERMINATE_FEASIBLE,
    KTR_MIP_HEURISTIC_AUTO,
    KTR_MIP_HEURISTIC_NONE,
    KTR_MIP_HEURISTIC_FEASPUMP,
    KTR_MIP_HEURISTIC_MPEC,
    KTR_MIP_PSEUDOINIT_AUTO,
    KTR_MIP_PSEUDOINIT_AVE,
    KTR_MIP_PSEUDOINIT_STRONG,
    KTR_PAR_CONCURRENT_EVALS_NO,
    KTR_PAR_CONCURRENT_EVALS_YES

const KTR_INFBOUND = Compat.@compat Float64(1.0e20)
const KTR_OBJGOAL_MINIMIZE = Compat.@compat Int32(0)
const KTR_OBJGOAL_MAXIMIZE = Compat.@compat Int32(1)
const KTR_OBJTYPE_GENERAL = Compat.@compat Int32(0)
const KTR_OBJTYPE_LINEAR = Compat.@compat Int32(1)
const KTR_OBJTYPE_QUADRATIC = Compat.@compat Int32(2)
const KTR_CONTYPE_GENERAL = Compat.@compat Int32(0)
const KTR_CONTYPE_LINEAR = Compat.@compat Int32(1)
const KTR_CONTYPE_QUADRATIC = Compat.@compat Int32(2)
const KTR_VARTYPE_CONTINUOUS = Compat.@compat Int32(0)
const KTR_VARTYPE_INTEGER = Compat.@compat Int32(1)
const KTR_VARTYPE_BINARY = Compat.@compat Int32(2)
const KTR_FNTYPE_UNCERTAIN = Compat.@compat Int32(0)
const KTR_FNTYPE_CONVEX = Compat.@compat Int32(1)
const KTR_FNTYPE_NONCONVEX = Compat.@compat Int32(2)
const KTR_RC_BEGINEND = Compat.@compat Int32(0)
const KTR_RC_EVALFC = Compat.@compat Int32(1)
const KTR_RC_EVALGA = Compat.@compat Int32(2)
const KTR_RC_EVALH = Compat.@compat Int32(3)
const KTR_RC_EVALX0 = Compat.@compat Int32(4)
const KTR_RC_FINISHED = Compat.@compat Int32(5)
const KTR_RC_NEWPOINT = Compat.@compat Int32(6)
const KTR_RC_EVALHV = Compat.@compat Int32(7)
const KTR_RC_EVALH_NO_F = Compat.@compat Int32(8)
const KTR_RC_EVALHV_NO_F = Compat.@compat Int32(9)
const KTR_RC_NODE = Compat.@compat Int32(10)
const KTR_RC_MSPROCESS = Compat.@compat Int32(11)
const KTR_RC_OPTIMAL = Compat.@compat Int32(0)
const KTR_RC_NEAR_OPT = Compat.@compat Int32(-100)
const KTR_RC_FEAS_XTOL = Compat.@compat Int32(-101)
const KTR_RC_FEAS_NO_IMPROVE = Compat.@compat Int32(-102)
const KTR_RC_FEAS_FTOL = Compat.@compat Int32(-103)
const KTR_RC_INFEASIBLE = Compat.@compat Int32(-200)
const KTR_RC_INFEAS_XTOL = Compat.@compat Int32(-201)
const KTR_RC_INFEAS_NO_IMPROVE = Compat.@compat Int32(-202)
const KTR_RC_INFEAS_MULTISTART = Compat.@compat Int32(-203)
const KTR_RC_INFEAS_CON_BOUNDS = Compat.@compat Int32(-204)
const KTR_RC_INFEAS_VAR_BOUNDS = Compat.@compat Int32(-205)
const KTR_RC_UNBOUNDED = Compat.@compat Int32(-300)
const KTR_RC_ITER_LIMIT = Compat.@compat Int32(-400)
const KTR_RC_TIME_LIMIT = Compat.@compat Int32(-401)
const KTR_RC_FEVAL_LIMIT = Compat.@compat Int32(-402)
const KTR_RC_MIP_EXH = Compat.@compat Int32(-403)
const KTR_RC_MIP_FEAS_TERM = Compat.@compat Int32(-404)
const KTR_RC_MIP_SOLVE_LIMIT = Compat.@compat Int32(-405)
const KTR_RC_MIP_NODE_LIMIT = Compat.@compat Int32(-406)
const KTR_RC_CALLBACK_ERR = Compat.@compat Int32(-500)
const KTR_RC_LP_SOLVER_ERR = Compat.@compat Int32(-501)
const KTR_RC_EVAL_ERR = Compat.@compat Int32(-502)
const KTR_RC_OUT_OF_MEMORY = Compat.@compat Int32(-503)
const KTR_RC_USER_TERMINATION = Compat.@compat Int32(-504)
const KTR_RC_OPEN_FILE_ERR = Compat.@compat Int32(-505)
const KTR_RC_BAD_N_OR_F = Compat.@compat Int32(-506)
const KTR_RC_BAD_CONSTRAINT = Compat.@compat Int32(-507)
const KTR_RC_BAD_JACOBIAN = Compat.@compat Int32(-508)
const KTR_RC_BAD_HESSIAN = Compat.@compat Int32(-509)
const KTR_RC_BAD_CON_INDEX = Compat.@compat Int32(-510)
const KTR_RC_BAD_JAC_INDEX = Compat.@compat Int32(-511)
const KTR_RC_BAD_HESS_INDEX = Compat.@compat Int32(-512)
const KTR_RC_BAD_CON_BOUNDS = Compat.@compat Int32(-513)
const KTR_RC_BAD_VAR_BOUNDS = Compat.@compat Int32(-514)
const KTR_RC_ILLEGAL_CALL = Compat.@compat Int32(-515)
const KTR_RC_BAD_KCPTR = Compat.@compat Int32(-516)
const KTR_RC_NULL_POINTER = Compat.@compat Int32(-517)
const KTR_RC_BAD_INIT_VALUE = Compat.@compat Int32(-518)
const KTR_RC_NEWPOINT_HALT = Compat.@compat Int32(-519)
const KTR_RC_BAD_LICENSE = Compat.@compat Int32(-520)
const KTR_RC_BAD_PARAMINPUT = Compat.@compat Int32(-521)
const KTR_RC_LINEAR_SOLVER_ERR = Compat.@compat Int32(-522)
const KTR_RC_INTERNAL_ERROR = Compat.@compat Int32(-600)
const KTR_PARAM_NEWPOINT = Compat.@compat Int32(1001)
const KTR_PARAM_HONORBNDS = Compat.@compat Int32(1002)
const KTR_PARAM_ALGORITHM = Compat.@compat Int32(1003)
const KTR_PARAM_ALG = Compat.@compat Int32(1003)
const KTR_PARAM_BAR_MURULE = Compat.@compat Int32(1004)
const KTR_PARAM_BARRULE = Compat.@compat Int32(1004)
const KTR_PARAM_BAR_FEASIBLE = Compat.@compat Int32(1006)
const KTR_PARAM_FEASIBLE = Compat.@compat Int32(1006)
const KTR_PARAM_GRADOPT = Compat.@compat Int32(1007)
const KTR_PARAM_HESSOPT = Compat.@compat Int32(1008)
const KTR_PARAM_BAR_INITPT = Compat.@compat Int32(1009)
const KTR_PARAM_LPSOLVER = Compat.@compat Int32(1012)
const KTR_PARAM_MAXCGIT = Compat.@compat Int32(1013)
const KTR_PARAM_MAXIT = Compat.@compat Int32(1014)
const KTR_PARAM_OUTLEV = Compat.@compat Int32(1015)
const KTR_PARAM_OUTMODE = Compat.@compat Int32(1016)
const KTR_PARAM_SCALE = Compat.@compat Int32(1017)
const KTR_PARAM_SHIFTINIT = Compat.@compat Int32(1018)
const KTR_PARAM_SOC = Compat.@compat Int32(1019)
const KTR_PARAM_DELTA = Compat.@compat Int32(1020)
const KTR_PARAM_BAR_FEASMODETOL = Compat.@compat Int32(1021)
const KTR_PARAM_FEASMODETOL = Compat.@compat Int32(1021)
const KTR_PARAM_FEASTOL = Compat.@compat Int32(1022)
const KTR_PARAM_FEASTOLABS = Compat.@compat Int32(1023)
const KTR_PARAM_MAXTIMECPU = Compat.@compat Int32(1024)
const KTR_PARAM_BAR_INITMU = Compat.@compat Int32(1025)
const KTR_PARAM_MU = Compat.@compat Int32(1025)
const KTR_PARAM_OBJRANGE = Compat.@compat Int32(1026)
const KTR_PARAM_OPTTOL = Compat.@compat Int32(1027)
const KTR_PARAM_OPTTOLABS = Compat.@compat Int32(1028)
const KTR_PARAM_PIVOT = Compat.@compat Int32(1029)
const KTR_PARAM_XTOL = Compat.@compat Int32(1030)
const KTR_PARAM_DEBUG = Compat.@compat Int32(1031)
const KTR_PARAM_MULTISTART = Compat.@compat Int32(1033)
const KTR_PARAM_MSMAXSOLVES = Compat.@compat Int32(1034)
const KTR_PARAM_MSMAXBNDRANGE = Compat.@compat Int32(1035)
const KTR_PARAM_MSMAXTIMECPU = Compat.@compat Int32(1036)
const KTR_PARAM_MSMAXTIMEREAL = Compat.@compat Int32(1037)
const KTR_PARAM_LMSIZE = Compat.@compat Int32(1038)
const KTR_PARAM_BAR_MAXCROSSIT = Compat.@compat Int32(1039)
const KTR_PARAM_MAXCROSSIT = Compat.@compat Int32(1039)
const KTR_PARAM_MAXTIMEREAL = Compat.@compat Int32(1040)
const KTR_PARAM_PRECOND = Compat.@compat Int32(1041)
const KTR_PARAM_BLASOPTION = Compat.@compat Int32(1042)
const KTR_PARAM_BAR_MAXREFACTOR = Compat.@compat Int32(1043)
const KTR_PARAM_BAR_MAXBACKTRACK = Compat.@compat Int32(1044)
const KTR_PARAM_BLASOPTIONLIB = Compat.@compat Int32(1045)
const KTR_PARAM_OUTAPPEND = Compat.@compat Int32(1046)
const KTR_PARAM_OUTDIR = Compat.@compat Int32(1047)
const KTR_PARAM_CPLEXLIB = Compat.@compat Int32(1048)
const KTR_PARAM_BAR_PENRULE = Compat.@compat Int32(1049)
const KTR_PARAM_BAR_PENCONS = Compat.@compat Int32(1050)
const KTR_PARAM_MSNUMTOSAVE = Compat.@compat Int32(1051)
const KTR_PARAM_MSSAVETOL = Compat.@compat Int32(1052)
const KTR_PARAM_PRESOLVEDEBUG = Compat.@compat Int32(1053)
const KTR_PARAM_MSTERMINATE = Compat.@compat Int32(1054)
const KTR_PARAM_MSSTARTPTRANGE = Compat.@compat Int32(1055)
const KTR_PARAM_INFEASTOL = Compat.@compat Int32(1056)
const KTR_PARAM_LINSOLVER = Compat.@compat Int32(1057)
const KTR_PARAM_BAR_DIRECTINTERVAL = Compat.@compat Int32(1058)
const KTR_PARAM_PRESOLVE = Compat.@compat Int32(1059)
const KTR_PARAM_PRESOLVE_TOL = Compat.@compat Int32(1060)
const KTR_PARAM_BAR_SWITCHRULE = Compat.@compat Int32(1061)
const KTR_PARAM_HESSIAN_NO_F = Compat.@compat Int32(1062)
const KTR_PARAM_MA_TERMINATE = Compat.@compat Int32(1063)
const KTR_PARAM_MA_MAXTIMECPU = Compat.@compat Int32(1064)
const KTR_PARAM_MA_MAXTIMEREAL = Compat.@compat Int32(1065)
const KTR_PARAM_MSSEED = Compat.@compat Int32(1066)
const KTR_PARAM_MA_OUTSUB = Compat.@compat Int32(1067)
const KTR_PARAM_MS_OUTSUB = Compat.@compat Int32(1068)
const KTR_PARAM_XPRESSLIB = Compat.@compat Int32(1069)
const KTR_PARAM_TUNER = Compat.@compat Int32(1070)
const KTR_PARAM_TUNER_OPTIONSFILE = Compat.@compat Int32(1071)
const KTR_PARAM_TUNER_MAXTIMECPU = Compat.@compat Int32(1072)
const KTR_PARAM_TUNER_MAXTIMEREAL = Compat.@compat Int32(1073)
const KTR_PARAM_TUNER_OUTSUB = Compat.@compat Int32(1074)
const KTR_PARAM_TUNER_TERMINATE = Compat.@compat Int32(1075)
const KTR_PARAM_LINSOLVER_OOC = Compat.@compat Int32(1076)
const KTR_PARAM_BAR_RELAXCONS = Compat.@compat Int32(1077)
const KTR_PARAM_MIP_METHOD = Compat.@compat Int32(2001)
const KTR_PARAM_MIP_BRANCHRULE = Compat.@compat Int32(2002)
const KTR_PARAM_MIP_SELECTRULE = Compat.@compat Int32(2003)
const KTR_PARAM_MIP_INTGAPABS = Compat.@compat Int32(2004)
const KTR_PARAM_MIP_INTGAPREL = Compat.@compat Int32(2005)
const KTR_PARAM_MIP_MAXTIMECPU = Compat.@compat Int32(2006)
const KTR_PARAM_MIP_MAXTIMEREAL = Compat.@compat Int32(2007)
const KTR_PARAM_MIP_MAXSOLVES = Compat.@compat Int32(2008)
const KTR_PARAM_MIP_INTEGERTOL = Compat.@compat Int32(2009)
const KTR_PARAM_MIP_OUTLEVEL = Compat.@compat Int32(2010)
const KTR_PARAM_MIP_OUTINTERVAL = Compat.@compat Int32(2011)
const KTR_PARAM_MIP_OUTSUB = Compat.@compat Int32(2012)
const KTR_PARAM_MIP_DEBUG = Compat.@compat Int32(2013)
const KTR_PARAM_MIP_IMPLICATNS = Compat.@compat Int32(2014)
const KTR_PARAM_MIP_GUB_BRANCH = Compat.@compat Int32(2015)
const KTR_PARAM_MIP_KNAPSACK = Compat.@compat Int32(2016)
const KTR_PARAM_MIP_ROUNDING = Compat.@compat Int32(2017)
const KTR_PARAM_MIP_ROOTALG = Compat.@compat Int32(2018)
const KTR_PARAM_MIP_LPALG = Compat.@compat Int32(2019)
const KTR_PARAM_MIP_TERMINATE = Compat.@compat Int32(2020)
const KTR_PARAM_MIP_MAXNODES = Compat.@compat Int32(2021)
const KTR_PARAM_MIP_HEURISTIC = Compat.@compat Int32(2022)
const KTR_PARAM_MIP_HEUR_MAXIT = Compat.@compat Int32(2023)
const KTR_PARAM_MIP_HEUR_MAXTIMECPU = Compat.@compat Int32(2024)
const KTR_PARAM_MIP_HEUR_MAXTIMEREAL = Compat.@compat Int32(2025)
const KTR_PARAM_MIP_PSEUDOINIT = Compat.@compat Int32(2026)
const KTR_PARAM_MIP_STRONG_MAXIT = Compat.@compat Int32(2027)
const KTR_PARAM_MIP_STRONG_CANDLIM = Compat.@compat Int32(2028)
const KTR_PARAM_MIP_STRONG_LEVEL = Compat.@compat Int32(2029)
const KTR_PARAM_PAR_NUMTHREADS = Compat.@compat Int32(3001)
const KTR_PARAM_PAR_CONCURRENT_EVALS = Compat.@compat Int32(3002)
const KTR_PARAM_PAR_BLASNUMTHREADS = Compat.@compat Int32(3003)
const KTR_PARAM_PAR_LSNUMTHREADS = Compat.@compat Int32(3004)

const KTR_NEWPOINT_NONE = Compat.@compat Int32(0)
const KTR_NEWPOINT_SAVEONE = Compat.@compat Int32(1)
const KTR_NEWPOINT_SAVEALL = Compat.@compat Int32(2)
const KTR_NEWPOINT_USER = Compat.@compat Int32(3)
const KTR_HONORBNDS_NO = Compat.@compat Int32(0)
const KTR_HONORBNDS_ALWAYS = Compat.@compat Int32(1)
const KTR_HONORBNDS_INITPT = Compat.@compat Int32(2)
const KTR_ALG_AUTOMATIC = Compat.@compat Int32(0)
const KTR_ALG_AUTO = Compat.@compat Int32(0)
const KTR_ALG_BAR_DIRECT = Compat.@compat Int32(1)
const KTR_ALG_BAR_CG = Compat.@compat Int32(2)
const KTR_ALG_ACT_CG = Compat.@compat Int32(3)
const KTR_ALG_IPDIRECT = Compat.@compat Int32(1)
const KTR_ALG_IPCG = Compat.@compat Int32(2)
const KTR_ALG_ACTIVE = Compat.@compat Int32(3)
const KTR_ALG_MULTI = Compat.@compat Int32(5)
const KTR_BAR_MURULE_AUTOMATIC = Compat.@compat Int32(0)
const KTR_BAR_MURULE_AUTO = Compat.@compat Int32(0)
const KTR_BAR_MURULE_MONOTONE = Compat.@compat Int32(1)
const KTR_BAR_MURULE_ADAPTIVE = Compat.@compat Int32(2)
const KTR_BAR_MURULE_PROBING = Compat.@compat Int32(3)
const KTR_BAR_MURULE_DAMPMPC = Compat.@compat Int32(4)
const KTR_BAR_MURULE_FULLMPC = Compat.@compat Int32(5)
const KTR_BAR_MURULE_QUALITY = Compat.@compat Int32(6)
const KTR_BAR_FEASIBLE_NO = Compat.@compat Int32(0)
const KTR_BAR_FEASIBLE_STAY = Compat.@compat Int32(1)
const KTR_BAR_FEASIBLE_GET = Compat.@compat Int32(2)
const KTR_BAR_FEASIBLE_GET_STAY = Compat.@compat Int32(3)
const KTR_FEASIBLE_NO = Compat.@compat Int32(0)
const KTR_FEASIBLE_ALWAYS = Compat.@compat Int32(1)
const KTR_GRADOPT_EXACT = Compat.@compat Int32(1)
const KTR_GRADOPT_FORWARD = Compat.@compat Int32(2)
const KTR_GRADOPT_CENTRAL = Compat.@compat Int32(3)
const KTR_GRADOPT_USER_FORWARD = Compat.@compat Int32(4)
const KTR_GRADOPT_USER_CENTRAL = Compat.@compat Int32(5)
const KTR_HESSOPT_EXACT = Compat.@compat Int32(1)
const KTR_HESSOPT_BFGS = Compat.@compat Int32(2)
const KTR_HESSOPT_SR1 = Compat.@compat Int32(3)
const KTR_HESSOPT_FINITE_DIFF = Compat.@compat Int32(4)
const KTR_HESSOPT_PRODUCT = Compat.@compat Int32(5)
const KTR_HESSOPT_LBFGS = Compat.@compat Int32(6)
const KTR_BAR_INITPT_AUTO = Compat.@compat Int32(0)
const KTR_BAR_INITPT_YES = Compat.@compat Int32(1)
const KTR_BAR_INITPT_STRAT1 = Compat.@compat Int32(1)
const KTR_BAR_INITPT_NO = Compat.@compat Int32(2)
const KTR_BAR_INITPT_STRAT2 = Compat.@compat Int32(2)
const KTR_BAR_INITPT_STRAT3 = Compat.@compat Int32(3)
const KTR_LP_INTERNAL = Compat.@compat Int32(1)
const KTR_LP_CPLEX = Compat.@compat Int32(2)
const KTR_LP_XPRESS = Compat.@compat Int32(3)
const KTR_OUTLEV_NONE = Compat.@compat Int32(0)
const KTR_OUTLEV_SUMMARY = Compat.@compat Int32(1)
const KTR_OUTLEV_MAJORIT10 = Compat.@compat Int32(2)
const KTR_OUTLEV_ITER_10 = Compat.@compat Int32(2)
const KTR_OUTLEV_MAJORIT = Compat.@compat Int32(3)
const KTR_OUTLEV_ITER = Compat.@compat Int32(3)
const KTR_OUTLEV_ALLIT = Compat.@compat Int32(4)
const KTR_OUTLEV_ITER_VERBOSE = Compat.@compat Int32(4)
const KTR_OUTLEV_ALLIT_X = Compat.@compat Int32(5)
const KTR_OUTLEV_ITER_X = Compat.@compat Int32(5)
const KTR_OUTLEV_ALL = Compat.@compat Int32(6)
const KTR_OUTMODE_SCREEN = Compat.@compat Int32(0)
const KTR_OUTMODE_FILE = Compat.@compat Int32(1)
const KTR_OUTMODE_BOTH = Compat.@compat Int32(2)
const KTR_SCALE_NEVER = Compat.@compat Int32(0)
const KTR_SCALE_ALLOW = Compat.@compat Int32(1)
const KTR_SOC_NO = Compat.@compat Int32(0)
const KTR_SOC_MAYBE = Compat.@compat Int32(1)
const KTR_SOC_YES = Compat.@compat Int32(2)
const KTR_DEBUG_NONE = Compat.@compat Int32(0)
const KTR_DEBUG_PROBLEM = Compat.@compat Int32(1)
const KTR_DEBUG_EXECUTION = Compat.@compat Int32(2)
const KTR_MULTISTART_NO = Compat.@compat Int32(0)
const KTR_MULTISTART_YES = Compat.@compat Int32(1)
const KTR_PRECOND_NONE = Compat.@compat Int32(0)
const KTR_PRECOND_CHOL = Compat.@compat Int32(1)
const KTR_BLASOPTION_KNITRO = Compat.@compat Int32(0)
const KTR_BLASOPTION_INTEL = Compat.@compat Int32(1)
const KTR_BLASOPTION_DYNAMIC = Compat.@compat Int32(2)
const KTR_OUTAPPEND_NO = Compat.@compat Int32(0)
const KTR_OUTAPPEND_YES = Compat.@compat Int32(1)
const KTR_BAR_PENRULE_AUTO = Compat.@compat Int32(0)
const KTR_BAR_PENRULE_SINGLE = Compat.@compat Int32(1)
const KTR_BAR_PENRULE_FLEX = Compat.@compat Int32(2)
const KTR_BAR_PENCONS_AUTO = Compat.@compat Int32(0)
const KTR_BAR_PENCONS_NONE = Compat.@compat Int32(1)
const KTR_BAR_PENCONS_ALL = Compat.@compat Int32(2)
const KTR_BAR_PENCONS_EQUALITIES = Compat.@compat Int32(3)
const KTR_BAR_PENCONS_INFEAS = Compat.@compat Int32(4)
const KTR_PRESOLVEDBG_NONE = Compat.@compat Int32(0)
const KTR_PRESOLVEDBG_BASIC = Compat.@compat Int32(1)
const KTR_PRESOLVEDBG_VERBOSE = Compat.@compat Int32(2)
const KTR_MSTERMINATE_MAXSOLVES = Compat.@compat Int32(0)
const KTR_MSTERMINATE_OPTIMAL = Compat.@compat Int32(1)
const KTR_MSTERMINATE_FEASIBLE = Compat.@compat Int32(2)
const KTR_LINSOLVER_AUTO = Compat.@compat Int32(0)
const KTR_LINSOLVER_INTERNAL = Compat.@compat Int32(1)
const KTR_LINSOLVER_HYBRID = Compat.@compat Int32(2)
const KTR_LINSOLVER_DENSEQR = Compat.@compat Int32(3)
const KTR_LINSOLVER_MA27 = Compat.@compat Int32(4)
const KTR_LINSOLVER_MA57 = Compat.@compat Int32(5)
const KTR_LINSOLVER_MKLPARDISO = Compat.@compat Int32(6)
const KTR_PRESOLVE_NONE = Compat.@compat Int32(0)
const KTR_PRESOLVE_BASIC = Compat.@compat Int32(1)
const KTR_PRESOLVE_ADVANCED = Compat.@compat Int32(2)
const KTR_BAR_SWITCHRULE_AUTO = Compat.@compat Int32(0)
const KTR_BAR_SWITCHRULE_NEVER = Compat.@compat Int32(1)
const KTR_BAR_SWITCHRULE_LEVEL1 = Compat.@compat Int32(2)
const KTR_BAR_SWITCHRULE_LEVEL2 = Compat.@compat Int32(3)
const KTR_HESSIAN_NO_F_FORBID = Compat.@compat Int32(0)
const KTR_HESSIAN_NO_F_ALLOW = Compat.@compat Int32(1)
const KTR_MA_TERMINATE_ALL = Compat.@compat Int32(0)
const KTR_MA_TERMINATE_OPTIMAL = Compat.@compat Int32(1)
const KTR_MA_TERMINATE_FEASIBLE = Compat.@compat Int32(2)
const KTR_MA_OUTSUB_NONE = Compat.@compat Int32(0)
const KTR_MA_OUTSUB_YES = Compat.@compat Int32(1)
const KTR_MS_OUTSUB_NONE = Compat.@compat Int32(0)
const KTR_MS_OUTSUB_YES = Compat.@compat Int32(1)
const KTR_TUNER_OFF = Compat.@compat Int32(0)
const KTR_TUNER_ON = Compat.@compat Int32(1)
const KTR_TUNER_OUTSUB_NONE = Compat.@compat Int32(0)
const KTR_TUNER_OUTSUB_YES = Compat.@compat Int32(1)
const KTR_TUNER_OUTSUB_SUMMARY = Compat.@compat Int32(1)
const KTR_TUNER_OUTSUB_ALL = Compat.@compat Int32(2)
const KTR_TUNER_TERMINATE_ALL = Compat.@compat Int32(0)
const KTR_TUNER_TERMINATE_OPTIMAL = Compat.@compat Int32(1)
const KTR_TUNER_TERMINATE_FEASIBLE = Compat.@compat Int32(2)
const KTR_LINSOLVER_OOC_NO = Compat.@compat Int32(0)
const KTR_LINSOLVER_OOC_MAYBE = Compat.@compat Int32(1)
const KTR_LINSOLVER_OOC_YES = Compat.@compat Int32(2)
const KTR_BAR_RELAXCONS_NONE = Compat.@compat Int32(0)
const KTR_BAR_RELAXCONS_EQS = Compat.@compat Int32(1)
const KTR_BAR_RELAXCONS_INEQS = Compat.@compat Int32(2)
const KTR_BAR_RELAXCONS_ALL = Compat.@compat Int32(3)
const KTR_MIP_METHOD_AUTO = Compat.@compat Int32(0)
const KTR_MIP_METHOD_BB = Compat.@compat Int32(1)
const KTR_MIP_METHOD_HQG = Compat.@compat Int32(2)
const KTR_MIP_BRANCH_AUTO = Compat.@compat Int32(0)
const KTR_MIP_BRANCH_MOSTFRAC = Compat.@compat Int32(1)
const KTR_MIP_BRANCH_PSEUDOCOST = Compat.@compat Int32(2)
const KTR_MIP_BRANCH_STRONG = Compat.@compat Int32(3)
const KTR_MIP_SEL_AUTO = Compat.@compat Int32(0)
const KTR_MIP_SEL_DEPTHFIRST = Compat.@compat Int32(1)
const KTR_MIP_SEL_BESTBOUND = Compat.@compat Int32(2)
const KTR_MIP_SEL_COMBO_1 = Compat.@compat Int32(3)
const KTR_MIP_OUTLEVEL_NONE = Compat.@compat Int32(0)
const KTR_MIP_OUTLEVEL_ITERS = Compat.@compat Int32(1)
const KTR_MIP_OUTLEVEL_ITERSTIME = Compat.@compat Int32(2)
const KTR_MIP_OUTSUB_NONE = Compat.@compat Int32(0)
const KTR_MIP_OUTSUB_YES = Compat.@compat Int32(1)
const KTR_MIP_OUTSUB_YESPROB = Compat.@compat Int32(2)
const KTR_MIP_DEBUG_NONE = Compat.@compat Int32(0)
const KTR_MIP_DEBUG_ALL = Compat.@compat Int32(1)
const KTR_MIP_IMPLICATNS_NO = Compat.@compat Int32(0)
const KTR_MIP_IMPLICATNS_YES = Compat.@compat Int32(1)
const KTR_MIP_GUB_BRANCH_NO = Compat.@compat Int32(0)
const KTR_MIP_GUB_BRANCH_YES = Compat.@compat Int32(1)
const KTR_MIP_KNAPSACK_NO = Compat.@compat Int32(0)
const KTR_MIP_KNAPSACK_INEQ = Compat.@compat Int32(1)
const KTR_MIP_KNAPSACK_INEQ_EQ = Compat.@compat Int32(2)
const KTR_MIP_ROUND_AUTO = Compat.@compat Int32(0)
const KTR_MIP_ROUND_NONE = Compat.@compat Int32(1)
const KTR_MIP_ROUND_HEURISTIC = Compat.@compat Int32(2)
const KTR_MIP_ROUND_NLP_SOME = Compat.@compat Int32(3)
const KTR_MIP_ROUND_NLP_ALWAYS = Compat.@compat Int32(4)
const KTR_MIP_ROOTALG_AUTO = Compat.@compat Int32(0)
const KTR_MIP_ROOTALG_BAR_DIRECT = Compat.@compat Int32(1)
const KTR_MIP_ROOTALG_BAR_CG = Compat.@compat Int32(2)
const KTR_MIP_ROOTALG_ACT_CG = Compat.@compat Int32(3)
const KTR_MIP_LPALG_AUTO = Compat.@compat Int32(0)
const KTR_MIP_LPALG_BAR_DIRECT = Compat.@compat Int32(1)
const KTR_MIP_LPALG_BAR_CG = Compat.@compat Int32(2)
const KTR_MIP_LPALG_ACT_CG = Compat.@compat Int32(3)
const KTR_MIP_TERMINATE_OPTIMAL = Compat.@compat Int32(0)
const KTR_MIP_TERMINATE_FEASIBLE = Compat.@compat Int32(1)
const KTR_MIP_HEURISTIC_AUTO = Compat.@compat Int32(0)
const KTR_MIP_HEURISTIC_NONE = Compat.@compat Int32(1)
const KTR_MIP_HEURISTIC_FEASPUMP = Compat.@compat Int32(2)
const KTR_MIP_HEURISTIC_MPEC = Compat.@compat Int32(3)
const KTR_MIP_PSEUDOINIT_AUTO = Compat.@compat Int32(0)
const KTR_MIP_PSEUDOINIT_AVE = Compat.@compat Int32(1)
const KTR_MIP_PSEUDOINIT_STRONG = Compat.@compat Int32(2)
const KTR_PAR_CONCURRENT_EVALS_NO = Compat.@compat Int32(0)
const KTR_PAR_CONCURRENT_EVALS_YES = Compat.@compat Int32(1)
